### ISSUE TITLE
Merging my fork?

### ISSUE THREAD

**Issue by jasonheecs** [rafritts/bunit#22]
Hi @atz3ro,

Great library you made here! I have found it really useful. I have forked this project and done some rather extensive refactoring of the code to make it more maintainable (IMHO) and fix some bugs with the Line numbers reporting and error messages. [Please refer to my fork.](https://github.com/jasonheecs/BashScriptTestingLibrary) It is a rather extensive refactoring of the codebase, but would you be interested in a pull request?

**Comment by rafritts** [comment]
Hey, are you kidding me? I'm thrilled someone else even uses it, let alone
enjoys it.  If those unit tests all still pass then I would say I am
definitely interested in a PR. I think your refactoring is fantastic. I
didn't know enough about Bash to implement the call back stuff, but this is
fantastic.

**Comment by rafritts** [comment]
@jasonheecs I took a deeper look at your changes, and I think they are great.  Whenever you're ready, make the PR and ill merge it.
