### ISSUE TITLE
TAP or Junit compatible output 

### ISSUE THREAD

**Issue by whatthefrog** [rafritts/bunit#40]
I have played with your nice bunit a bit.
it is very useful and simple to use.

One thing I would think to be a good addition is to have a TAP or junit like XML output so that this file can be parsed during a CI pipeline, and the name/number/state of the test suite be reported.

TAP
https://en.wikipedia.org/wiki/Test_Anything_Protocol

This is what I found to describe the expected junit.xml file format
https://github.com/windyroad/JUnit-Schema/blob/master/JUnit.xsd
https://stackoverflow.com/questions/4922867/what-is-the-junit-xml-format-specification-that-hudson-supports

What do you think ?

**Comment by rafritts** [comment]
I think this sounds like a great idea.  I think if we go down this road, we might want to support xml, json, and yaml.  Would you be willing to open a PR for xml support?
