### ISSUE TITLE
How to install correctly

### ISSUE THREAD

**Issue by Raphhh** [rafritts/bunit#45]
How and where in our project do we install this lib as a dev dependency and following the best practices?

For example, in javascript, we use the "npm" as dependencies manager: `$ npm install --save-dev this-super-lib` and "this-super-lib" goes directly in a specify directory "node_modules" and will be not build in the prod env. Is there something like this for shell dependencies?

There is no documentation in your README about installation best practices... :)

**Comment by rafritts** [comment]
Hey @Raphhh, I apologize for taking so long to respond.  This software doesnt have an installation.  Its simply a standalone file, `bunit.shl`.  The goal is that its useable even in the most extreme of locked down systems.
